### ISSUE TITLE
Error on schema creation

### ISSUE THREAD

**Issue by basilveerman** [sourcepole/pgversion#10]
Error when running [create_pgversion_schema](https://github.com/sourcepole/pgversion/blob/master/docs/create_pgversion_schema.sql)

```
psql:create_pgversion_schema.sql:1858: ERROR:  syntax error at or near "CREATE"
LINE 3: CREATE FUNCTION versions.pgvsmakebranch (IN in_table charact...
        ^
psql:create_pgversion_schema.sql:1860: ERROR:  function versions.pgvsmakebranch(character varying, character varying) does not exist
```

Looks like a missing semicolon [on line 1814](https://github.com/sourcepole/pgversion/blob/master/docs/create_pgversion_schema.sql#L1814)

**Comment by hdus** [comment]
fixed
