### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by knwin** [sourcepole/pgversion#12]
Below error message prompted when installed on QGIS 3.4

ImportError: PyQt4 classes cannot be imported in QGIS 3.x. Use PyQt5.QtCore or the version independent qgis.PyQt.QtCore import instead.

**Comment by hdus** [comment]
It looks like you are trying to load the plugin version for QGIS 2 into QGIS 3. Please install the correct plugin version for the correct QGIS version.

pg version 2.x.x QGIS 2
pgversion 3.x.x QGIS 3

**Comment by knwin** [comment]
I installed it from plugin manager of QGIS 3.4 and the version installed is shown as 3.0.6. The error message appear when I turn on the plugin

**Comment by hdus** [comment]
Please send the whole error message plus the python traceback.

**Comment by hdus** [comment]
If you had installed the plugin rev 2.x.x please remove it before installing the new revision

**Comment by hdus** [comment]
does it work after removing all pgversion stuff?

**Comment by HusseinKabbout** [comment]
I will be closing this issue because it is not up-to-date anymore. If you still have this issue please reopen it or create another ticket.
