### ISSUE TITLE
ModuleNotFoundError 'pgversion.dbtools.dbtools'

### ISSUE THREAD

**Issue by stepanosokin** [sourcepole/pgversion#13]
Hello!
After installation of QGIS plugin from repository I get an error 
ModuleNotFoundError: No module named 'pgversion.dbtools.dbtools'
And the plugin doesn't load. What can be the reason? 
I am using QGIS 3.4.13

**Comment by HusseinKabbout** [comment]
I installed the plugin from this repository and from the official QGIS Plugin repository. Both times the plugin could be loaded normaly. Could you give more information on how you installed the plugin? @stepanosokin

**Comment by hdus** [comment]
I close tis issue. When it still exists please feel free to reopen it.
