### ISSUE TITLE
"ERROR:  query string argument of EXECUTE is null" when the table is empty

### ISSUE THREAD

**Issue by useher** [sourcepole/pgversion#14]
If i try to initialize the versioning on an empty table the following error occurs:

`
select * from versions.pgvsinit('ne_1808.testtable');

ERROR:  query string argument of EXECUTE is null
CONTEXT:  PL/pgSQL function versions.pgvsinit(character varying) line 147 at EXECUTE
SQL state: 22004`

When i create content in QGIS, the initialization work as expected.
Question: Is this the intended behavior? For me, it would make more sense when a table can be versioned before content is put in, but i may be wrong with this. If this is intended, maybe a more readable message would be useful, especialliy in the QGIS-Plugin, which is often used by people with no database-knowledge.
 
best regards
Uwe Seher

**Comment by hdus** [comment]
It is not possible to set an empty table to the versioned state. In version 3.10.0 of the plugin a better error message is now displayed when trying to version an empty table.

**Comment by hdus** [comment]
I close tis issue. When it still exists please feel free to reopen it.
