### ISSUE TITLE
Error while upgrading from 1.8.1

### ISSUE THREAD

**Issue by andrespinog** [sourcepole/pgversion#15]
I have a previus version installed (1.8.1). When I try to upgrade the following message appears:

```
The Plugin expects pgvs revision 2.1.8 but DB-functions of revision 1.8.1 are installed. 
Please contact your DB-administrator to upgrade the DB-functions from the file:

C:/Users/andres.pino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgversion/docs/upgrade_pgversion_schema-2.8.1.sql

If you have appropriate DB permissions you can update the DB directly with click on DB-Update.

```

![image](https://user-images.githubusercontent.com/39016968/75715031-86dcc600-5cab-11ea-9749-477a61bd7d4f.png)

But "upgrade_pgversion_schema-2.8.1.sql" file doesn't exist in docs folder.

**Comment by hdus** [comment]
Please upgrade to the latest plugin version and report if the error still persists.

**Comment by hdus** [comment]
To update from pgvs version 1.8 to the current pgvs version you have to update all intermediate versions. This must be done. Therefore, as shown on the Update button, first update to version 2.1.2 etc.

**Comment by hdus** [comment]
I close tis issue. When it still exists please feel free to reopen it.
