### ISSUE TITLE
Error in pgvslogview()

### ISSUE THREAD

**Issue by pascatl** [sourcepole/pgversion#16]
I get an error when I click on "show logs" in the QGIS Plugin:
 
Python error console in QGIS:
```
 line 597, in doLogView
              for i in range(len(result["PROJECT"])):
             TypeError: 'NoneType' object is not subscriptable
```
So the result object is None. The result object is generated by executing following statement:
```
 sql = "select * from versions.pgvslogview('" + mySchema + "." + myTable.replace(
                '_version', '') + "') order by revision desc"
            result,  error = myDb.read(sql)
```
In the python console in QGIS I get following message:
```
invalid input syntax for type timestamp: "initial commit revision 0"
CONTEXT:  PL/pgSQL function versions.pgvslogview(character varying) line 37 at FOR over EXECUTE statement
```
So apparently the error is throwing by executing the function pgvslogview() in the following section:
```
 for logs IN  EXECUTE logViewQry
    LOOP

      return next logs;    
    end loop;   
```

What am I doing wrong or is something misconfigured?

**Comment by hdus** [comment]
Please describe exactly all steps that led to the error.

**Comment by pascatl** [comment]
I am using QGIS 3.10 and PgVersion 3.1.0. 
I initialized a versioned table and added it to an empty project. I modified the data, clicked on save and commited the changes by clicking on "Commit Changes" in the plugin menu. Afterward, by clicking on "Show Logs", the dialog doesn't opened and I got following error in the Python error log in QGIS:
```
Traceback (most recent call last):
              File "C:/Users/MyUserName/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgversion\pgVersion.py", line 597, in doLogView
              for i in range(len(result["PROJECT"])):
             TypeError: 'NoneType' object is not subscriptable
```
Keeping the QGIS built-in Python Console open, at the same time it shows following error:
```
invalid input syntax for type timestamp: "first change"
CONTEXT:  PL/pgSQL function versions.pgvslogview(character varying) line 36 at FOR over EXECUTE statement
```
The "result" object in python is created by the execution of 
`select * from versions.pgvslogview('" + mySchema + "." + myTable.replace(
                '_version', '') + "') order by revision desc"
            result,  error = myDb.read(sql)`
which returns None, because of the invalid syntax for type timestamp. Therefore the plugin can't handle the None object for opening the log dialog and raises the mentioned error.

My attempts:

- running the function pgvslogview('qualifier.tablename') directly in pgAdmin4. The same result:
```
invalid input syntax for type timestamp: "first change"
CONTEXT:  PL/pgSQL function versions.pgvslogview(character varying) line 36 at FOR over EXECUTE statement
```

- Removing  `to_timestamp(logt.systime/1000)` from pgvslogview() in the function definition in postgres and removing the entry `myItem.setText(1, str(result["DATUM"][i]))` from pgVersion.py in the plugin directory prevents the error and opens the log dialog in QGIS without an error, but of course without the timestamps in the log table.

**Comment by hdus** [comment]
Which PostgreSQL Version do you use?

**Comment by pascatl** [comment]
sorry, PostgreSQL 10.10

**Comment by hdus** [comment]
Is it possible to send the mentioned dataset?

**Comment by pascatl** [comment]
[versionierung_dump.zip](https://github.com/sourcepole/pgversion/files/5061624/versionierung_dump.zip)

**Comment by hdus** [comment]
Please upgrade your database with the attached diff and report the result.
[upgrade_pgversion_schema-2.1.9.zip](https://github.com/sourcepole/pgversion/files/5061970/upgrade_pgversion_schema-2.1.9.zip)

**Comment by pascatl** [comment]
Now it works :)
Thank you so much for your help!
