### ISSUE TITLE
Swapped User and Log-Message in LogView

### ISSUE THREAD

**Issue by pascatl** [sourcepole/pgversion#17]
QGIS 3.10
PgVersion 3.1.0
Postgres 10.10

Currently the user entries are in the column "Log-Message" and the log-message entries in the column "User":

![image](https://user-images.githubusercontent.com/17616165/90007181-8c96f880-dc9a-11ea-8e58-3edcadd7d5f2.png)

Looks like swapping the keys "PROJECT" and "LOGMSG" in line 600+601 and 633+634 in pgVersion.py solves the issue.

**Comment by hdus** [comment]
I have published a new release 3.1.1 of the plugin at the QGIS plugin repository. Please upgrade your DB with the attached sql code.
[upgrade_pgversion_schema-2.1.9.zip](https://github.com/sourcepole/pgversion/files/5062406/upgrade_pgversion_schema-2.1.9.zip)

**Comment by pascatl** [comment]
It works, thank you!
