### ISSUE TITLE
QGIS-Authentification credentials asked multiple times when using the plugin

### ISSUE THREAD

**Issue by useher** [sourcepole/pgversion#19]
Hello!
I come back on issue #3, because we see the same behavior and there was no solution provided in the ticket. We use the plugin version 3.1.1 installed via the qgis plugin mechanism. 
We use normaly authentification with master password in QGIS and several database connections. So no question for credentials should occur. When opening a project with the running pgversion plugin for every layer an authentification dialog appears, multiple times for the same database and/or layer. 
We see this behavior since QGIS-Version 3.6/8 and on several openSuse and Ubuntu distributions.

**Comment by hdus** [comment]
Have you set the rights as described in the help in chapter 1.3.3?

**Comment by useher** [comment]
Thank you. Didn't notice the passage, maybe an auto-update issue by me...
