### ISSUE TITLE
ERROR: Role »versions« already exists / FEHLER:  Rolle »versions« existiert bereits

### ISSUE THREAD

**Issue by dingausmwald** [sourcepole/pgversion#25]
The newest version of the qgis plugin seems to have a problem in "create_pgversion_schema.sql". It's correct in github. Tested with qgis 3.22.7 and pgversion 3.1.3

CREATE ROLE versions WITH 
	INHERIT
	ENCRYPTED PASSWORD '********';

appears two times in the plugin. In github the second is commented out. Same is for create table. There are maybe more typos.
I copied the version from github and it runs properly.

(i had more problems when tables are added, the plugin raises python errors, maybe unrelated, seems to have something to do with credentials, not sure)

**Comment by hdus** [comment]
Fixed in release 3.1.4
