### ISSUE TITLE
Fails to initialize

### ISSUE THREAD

**Issue by sggreener** [sourcepole/pgversion#27]
I click on "Prepare Layer for Versioning", 
then I say OK to:
"Do you want to create the version environment for the table test.heritageinterest?"
I get a (error) dialog box with the Initialisation error below (-----------------------).
From what I can see the view, "versions.test_heritageinterest_version_log" is not being created beforehand.
I am running PostgreSQL 15. Here is the result of SELECT postgis_full_version();
"POSTGIS=""3.3.2 3.3.2"" [EXTENSION] PGSQL=""150"" GEOS=""3.11.1-CAPI-1.17.1"" PROJ=""7.2.1"" LIBXML=""2.9.9"" LIBJSON=""0.12"" LIBPROTOBUF=""1.2.1"" WAGYU=""0.5.0 (Internal)"""
--------------------------------------------------------------------------------------------------
Initialisation of table test.heritageinterest failed!
                              
Error:
column v2.id does not exist
LINE 6: ... versions.test_heritageinterest_version_log v2 ON v2.id=v1.i...
                                                             ^
QUERY:  create or replace view test.heritageinterest_version_time as 
                SELECT row_number() OVER () AS rownum, 
                       to_timestamp(v1.systime/1000)::timestamp without time zone as start_time, 
                       to_timestamp(v2.systime/1000)::timestamp without time zone as end_time ,v1.wkb_geometry,v1.objectid,v1.name,v1.address,v1.email,v1.shape_leng,v1.shape_area,v1.chair,v1.phone,v1.contact,v1.contemail,v1.contphone
                FROM versions.test_heritageinterest_version_log v1
                LEFT JOIN versions.test_heritageinterest_version_log v2 ON v2.id=v1.id AND v2.action='delete'
                WHERE v1.action='insert'
CONTEXT:  PL/pgSQL function versions.pgvsinit(character varying) line 214 at EXECUTE

**Comment by hdus** [comment]
Please update the new plugin revision 3.3.2 from the QGIS plugin repository
