### ISSUE TITLE
Plugin don't work

### ISSUE THREAD

**Issue by BaBoWaGa** [sourcepole/pgversion#29]
Hi everyone I installed the plugin in QGIS and it appeared in the DB Manager, at a certain point it disappeared and if I try to use it from the gui in the toolbar it gives me the following error

AttributeError: 'NoneType' object has no attribute 'exists' 
Traceback (most recent call last):
  File "C:\Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgversion\pgVersion.py", line 289, in doInit
    if not self.tools.check_PGVS_revision(myDb):
  File "C:\Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgversion\pgVersionTools.py", line 447, in check_PGVS_revision
    if not myDb.exists('table', 'versions.version_tables'):
AttributeError: 'NoneType' object has no attribute 'exists'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.7-Firenze Firenze, fedae0eb52 

Python Path:
C:/PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python
C:/Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS32~1.7\apps\grass\grass82\etc\python
C:\Users\gianl\Documents
C:\Program Files\QGIS 3.28.7\bin\python39.zip
C:\PROGRA~1\QGIS32~1.7\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib
C:\Program Files\QGIS 3.28.7\bin
C:\PROGRA~1\QGIS32~1.7\apps\Python39
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\Pythonwin
C:/Users/gianl/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\gianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\gianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\milstd2525\extlibs
.
C:\Users\gianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SentinelHub\external\oauthlib-3.1.0-py2.py3-none-any.whl
C:\Users\gianl\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\SentinelHub\external\requests_oauthlib-1.3.0-py2.py3-none-any.whl
C:/Users/gianl/Work/Parabellum/ACUGIS/developer/geo/contemporary

Any ideas?

**Comment by tpo** [comment]
Restarting QGIS and/or reinstalling the plugin doesn't help?

**Comment by BaBoWaGa** [comment]
I did those tests but it didn't work, however I had to reset the PC (therefore also QGIS ) and now it works

**Comment by tpo** [comment]
Weird that - maybe out of memory?

**Comment by BaBoWaGa** [comment]
I really don't know what to think, at least now it works ;-)
