### ISSUE TITLE
"9999-01-01 00:00:00" - Problem with date in Initialisation

### ISSUE THREAD

**Issue by cycle4** [sourcepole/pgversion#30]
Hello !
Thanks for your work on this useful plugin !!
I have a problem when I try to initialise the versioning for a layer (prepare layer for versioning) : 

Error:
syntax error at or near "9999"
LINE 5:                          \'9999-01-01 00:00:00\'::timestamp ...
                                   ^
QUERY:  'create or replace view '||versionView||'_time as
                SELECT row_number() OVER () AS rownum,
                       to_timestamp(v1.systime/1000)::TIMESTAMP WITHOUT TIME ZONE  as start_time,
                       CASE WHEN v2.systime IS NULL THEN
                         \'9999-01-01 00:00:00\'::timestamp WITHOUT TIME ZONE
                       else
                         to_timestamp(v2.systime/1000)::TIMESTAMP WITHOUT TIME ZONE
                       END as end_time,
                       v1.*
                FROM '||versionLogTable||' v1
                LEFT JOIN '||versionLogTable||' v2 ON v2.'||myPkey||'=v1.'||myPkey||' AND v2.action=''delete'' and v1.revision <> v2.revision
                WHERE (v1.action=''insert'' or v1.action = ''update'') and v1.commit = True'
CONTEXT:  PL/pgSQL function versions.pgvsinit(character varying) line 214 at EXECUTE

I am using QGIS 3.28 on Windows 10 with the latest version of PostgreSQL alongside with PostGIS. I am a bit lost on how I can resolve this issue. Did someone went through that or has a solution ? 
Tell me if you need any more info
Thanks !

**Comment by hdus** [comment]
I've fixed the issue, please give it a try.

**Comment by hdus** [comment]
Please reinstall the pgvs system in your database.
