### ISSUE TITLE
pgvsinit type error

### ISSUE THREAD

**Issue by monodo** [sourcepole/pgversion#6]
On the way to make some tests with pgversion (master), the following error occured, but no on all layers:

---------------------------
DB-Error
---------------------------
ERREUR:  l'opérateur n'existe pas : text + integer
LINE 5: ... MAXVALUE 9223372036854775807 START '||testRec.max+1||' CACH...

In english, that would be translated as "operator does not exist: text + integer" what indicates a type issue.

@hdus : should I fix that with an explicit cast ?

**Comment by hdus** [comment]
Yes fix it and send a pull request would be nice.
