### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by tveinot** [sourcepole/pgversion#7]
So this might not be an issue that is within your scope for this product but maybe you can tell me what the error means...
So I used this on a simple postgis layer with no issues. PostgreSQL 9.6 PostGIS2.3.2 so I decided to try an use it on a larger more complicated database, well to me anyway. The database has main tables and many views with triggers and rules all defined. If you want to build an exact replica of this database just download giswater and create a sample database using the drainage model. 
Anyway when I try to version layers in this database I get.
![image](https://user-images.githubusercontent.com/26797978/31229223-625fea14-a9b6-11e7-9790-6093afb79534.png)
Anyway if you can help great, if not I understand; great tool even if it doesn't work with this database, I have many other layers to use it on.
Tyler

**Comment by hdus** [comment]
The error means, that your table sa_net.arc has no primary key defined. Define a primary key for thid table and try again.

**Comment by tveinot** [comment]
The primary key is actually defined;
![image](https://user-images.githubusercontent.com/26797978/31277554-e60216a0-aa77-11e7-8c91-a7b0c82e200b.png)
Or am I wrong in thinking that this is telling me the pk is arc_id? Anything else I can try?
Tyler

**Comment by hdus** [comment]
Do you use the recent version from github?

**Comment by hdus** [comment]
Can you send me the table dump without data please?

**Comment by tveinot** [comment]
I am using the version available from the QGIS repository, 2.1.35.

[arc.zip](https://github.com/sourcepole/pgversion/files/1363513/arc.zip)
I am not really smart with postgresql and I am incompetent when it comes to psql, hopefully what I sent you is sort of what you are looking for.
Tyler
